import Navbar from "@/shared/Navbar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Advance Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="mx-20">
          <div className="mb-5 mt-3">
            <Navbar></Navbar>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
