import GoToButton from "@/components/GoToButton";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div className="ml-10">
      <h2 className="mt-2">Home Page</h2>
      <GoToButton className="mt-2">
        Go to Settings
      </GoToButton>
    </div>
  );
};

export default HomePage;
