import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div>
      <h2>Home Page</h2>
    </div>
  );
};

export default HomePage;
