import type { Metadata } from "next";
import "../globals.css";

import Navbar from "@/shared/Navbar";

export const metadata: Metadata = {
  title: "Advance Next JS",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "bn" }];
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  // FIX: Changed "en" | "bn" to string to satisfy Next.js types
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;

  return (
    <html lang={lang}>
      <body>
        <div className="mx-20">
          <div className="mb-5 mt-3">
            <Navbar lang={lang}></Navbar>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
