// import Navbar from "@/shared/Navbar";
import type { Metadata } from "next";
import "../globals.css";

import Navbar from "@/shared/Navbar"

export const metadata: Metadata = {
  title: "Advance Next JS",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <div className="mx-20">
//           <div className="mb-5 mt-3">
//             <Navbar></Navbar>
//           </div>
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }


export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'bn' }]
}
 
export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "bn" }>;
}) {
  const { lang } = await params;
  return (
    <html lang={(await params).lang}>
      <body><div className="mx-20">
          <div className="mb-5 mt-3">
            <Navbar lang={lang}></Navbar>
          </div>
          {children}
        </div>
</body>
    </html>
  )
}